name: bulk_buyers
description: An eCommerce App.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.4"
  http: any


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/ellipse-1.png
    - assets/images/image-1.png
    - assets/images/image-bg.png
    - assets/images/welcome-bg.jpg
    - assets/images/icon-ionic-ios-arrow-dropright.png
    - assets/images/img-20181004-wa0006-3.png
    - assets/images/img-20181004-wa0006-5.png
    - assets/images/img-20181004-wa0006.png
    - assets/images/img-20181004-wa0006-2.png
    - assets/images/icon-ionic-ios-arrow-dropright.png
    - assets/images/icon-feather-shopping-cart-2.png
    - assets/images/icon-feather-home.png
    - assets/images/icon-feather-heart-2.png
    - assets/images/icon-feather-user-2.png
    - assets/images/icon-ionic-ios-menu.png
    - assets/images/icon-awesome-thumbs-up.png
    - assets/images/icon-feather-shopping-cart.png
    - assets/images/icon-feather-shopping-cart-3.png
    - assets/images/icon.png
    - assets/images/icon-material-add-shopping-cart.png
    - assets/images/broccoli-2.png
    - assets/images/005-vegetable-oil.png
    - assets/images/008-meat-1.png
    - assets/images/009-rice-1.png
    - assets/images/003-fish.png
    - assets/images/path-4725.png
    - assets/images/path-4735.png
    - assets/images/path-4734.png
    - assets/images/path-4739.png
    - assets/images/path-3968.png
    - assets/images/path-3969.png
    - assets/images/3j.png
    - assets/images/tomatoes-large.png
    - assets/images/tomatoes.png
    - assets/images/path-4738.png
    - assets/images/adobestock-159239671-2.png
    - assets/images/happycows-cow.png
    - assets/images/icn-fav.png
    - assets/images/ic-arrow-back-18px-2.png
    - assets/images/icon-material-add-shopping-cart-2.png
    - assets/images/mama-gold-rice.png
    - assets/images/happycows-cow-3.png
    - assets/images/icon-feather-home-2.png
    - assets/images/ic-add-48px.png
    - assets/images/ic-add-48px-2.png
    - assets/images/icon-feather-heart-3.png
    -  assets/images/icon-feather-heart.png
    - assets/images/icon-feather-user.png
    - assets/images/icon-feather-arrow-left.png
    - assets/images/line-copy-6.png
    - assets/images/list.png
    - assets/images/like-1.png
    - assets/images/path-4730.png
    - assets/images/path-4731.png
    - assets/images/icon-ionic-ios-help-circle-outline.png
    - assets/images/icon-ionic-ios-send.png
    - assets/images/icon-feather-home-3.png
    - assets/images/ic-add-48px.png
    - assets/images/happycows-cow-2.png
    - assets/images/boys.png
    - assets/images/icon-awesome-envelope.png
    - assets/images/icon-awesome-phone-alt.png
    - assets/images/icon-material-notifications-active.png
    - assets/images/icon-material-mode-edit.png
    - assets/images/icon-ionic-md-male.png
    - assets/images/icon-ionic-md-female.png
    - assets/images/icon-material-date-range.png
    - assets/images/icon-material-location-on.png
    - assets/images/icon-material-home.png
    - assets/images/2bp4pjr4wvimqcwjyimxje2cncgn5i4dwnhhsi56sr8.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
